// fetch table data
export const FETCH_TABLE_DATA = 'FETCH_TABLE_DATA';
export const FETCH_TABLE_DATA_OK = 'FETCH_TABLE_DATA_OK';
export const FETCH_TABLE_DATA_ERROR = 'FETCH_TABLE_DATA_ERROR';

// table actions
export const TABLE_GLOBAL_FILTER = 'TABLE_GLOBAL_FILTER';
export const TABLE_COLUMN_FILTER = 'TABLE_COLUMN_FILTER';
export const TABLE_SORT_BY_COLUMN = 'TABLE_SORT_BY_COLUMN';
export const TABLE_REMOVE_ROWS = 'TABLE_REMOVE_ROWS';

// table ui actions
export const TABLE_CHANGE_FILTERS_VISIBILITY = 'TABLE_CHANGE_FILTERS_VISIBILITY';
export const TABLE_CHANGE_VIRTUALIZATION = 'TABLE_CHANGE_VIRTUALIZATION';
export const TABLE_CHANGE_COLUMN_LIST = 'TABLE_CHANGE_COLUMN_LIST';
export const TABLE_CHANGE_FIXED_COLUMNS_COUNT = 'TABLE_CHANGE_FIXED_COLUMNS_COUNT';
